name: Build Cherry Kernel for cereus

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        sudo apt install -y wget bc build-essential make autoconf automake
        wget -q https://releases.linaro.org/components/toolchain/binaries/7.5-2019.12/arm-linux-gnueabihf/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz
        tar -xJf gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz
        mv gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf gcc
        rm gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz
        ARCH=arm make O=out cereus_defconfig
        ARCH=arm CROSS_COMPILE=$(pwd)/gcc/bin/arm-linux-gnueabihf- make O=out -j$(echo "$(nproc --all)+2" | bc)
        git clone https://github.com/minhducsun2002/AnyKernel3-cereus ak3 --depth 1 --single-branch -b cereus
        cp out/arch/arm/boot/zImage-dtb ak3
        cd ak3
        zip -r9 CherryKernel-Ionized-cereus.zip * -x .git README.md *placeholder
        cp CherryKernel-Ionized-cereus.zip ../
    - uses: actions/upload-artifact@v1
      with:
        name: CherryKernel-Ionized-cereus-${{ github.sha }}
        path: CherryKernel-Ionized-cereus.zip
